import { EntitySchema } from "typeorm";

export const chatAppEntities = EntitySchema(
    {
        name: "User",
        tablename:"user",
        columns:{
            id:{
                primary:true,
                type:'int',
                generated:true
            },
            username:{
                type:'varchar',
                nullable:true
            },
            password:{
                type:'varchar',
                nullable:true
            }
        }
    },
    {
        name: "Chat",
        tablename:"chat",
        columns:{
            id:{
                primary:true,
                type:'int',
                generated:true
            },
            name:{
                type:'varchar',
                nullable:true
            }
        }
    },
    {
        name: "Mensaje",
        tablename:"mensaje",
        columns:{
            id:{
                primary:true,
                type:'int',
                generated:true
            },
            content:{
                type:'varchar',
                nullable:true
            },
            user:{
                type:'int',
                nullable:false
            },
            chat:{
                type:'int',
                nullable:false
            }
        }
    },
    {
        name: "Participa",
        tablename:"participa",
        columns:{
            id:{
                primary:true,
                type:'int',
                generated:true
            },
            user:{
                type:'int',
                nullable:false
            },
            chat:{
                type:'int',
                nullable:false
            }
        }
    }
)